### PR TITLE
Update to 2.0.0

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by Calinou** [comment]
The patch shouldn't be necessary anymore with the latest Red Eclipse code base.

**Comment by AsciiWolf** [comment]
Build on arm and aarch64 failed with: `ninja: error: 'steam_lib-NOTFOUND', needed by 'redeclipse_server_linux', missing and no known rule to make it`

However, it built fine on x86_64, so it seems to be a bug. @Calinou Any idea? :-)

**Comment by Calinou** [comment]
@AsciiWolf The game requires OpenGL 3.0 (not OpenGL ES) to run, so feel free to skip the ARM and ARM64 builds. ARM hardware that supports plain OpenGL is very uncommon, so we probably shouldn't spend much time trying to support it.

**Comment by AsciiWolf** [comment]
So, it looks like that the steam lib/api is issue as well on x86_64. This is what I get when I try to run the Flatpak: `./redeclipse: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`

```
$ ldd /app/share/redeclipse/redeclipse
	linux-vdso.so.1 (0x00007ffca8d39000)
	librt.so.1 => /usr/lib/x86_64-linux-gnu/librt.so.1 (0x00007fdb49b58000)
	libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x00007fdb49b3e000)
	libSDL2-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007fdb499f2000)
	libSDL2_image-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0 (0x00007fdb499ce000)
	libSDL2_mixer-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so.0 (0x00007fdb499ae000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fdb49915000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fdb497cb000)
	libsteam_api.so => not found
	libdiscord-rpc.so => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdb495cb000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007fdb4947e000)
	libmvec.so.1 => /usr/lib/x86_64-linux-gnu/libmvec.so.1 (0x00007fdb49451000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007fdb49286000)
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdb49264000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdb4925e000)
	libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fdb49259000)
	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fdb49247000)
	libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007fdb4923c000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fdb491f7000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fdb491bd000)
	libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007fdb49125000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fdb490b5000)
	libwebp.so.7 => /usr/lib/x86_64-linux-gnu/libwebp.so.7 (0x00007fdb49044000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fdb49010000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fdb48ff9000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fdb48f3c000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fdb48f10000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdb4a572000)
	libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdb48ef6000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fdb48eeb000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fdb48ee3000)

$ ldd /app/share/redeclipse/redeclipse_server
	linux-vdso.so.1 (0x00007ffc6dd65000)
	libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x00007fa20f03e000)
	libsteam_api.so => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa20ee3e000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007fa20ecf1000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007fa20eb28000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa20f3d3000)
	libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa20eb0e000)
```

@Calinou Is it possible to specify in CMake not to build redeclipse against the steam and discord libs?

**Comment by Calinou** [comment]
@AsciiWolf `-DWANT_DISCORD=0 -DWANT_STEAM=0` should do the job.

**Comment by AsciiWolf** [comment]
Just tested the game and it now works fine! I am merging this PR as a little xmas gift to Flathub gamers. :-)

**Pull request merged**
